version: '3'
services:
  mysql:
    image: ${DB_ENGINE}:${DB_VERSION}
    container_name: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${PORT_EXPOSE}:3306'

  app:
    depends_on: 
      - mysql
    build: ./api
    #restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${MYSQL_DOCKER_PORT}
    stdin_open: true
    tty: true

volumes: 
  db: